### ISSUE TITLE
Mentions on hidden repository

### ISSUE THREAD

**Issue by martinnj** [axeloh/Django_Project#1]
Hey mate (@axeloh )

Sorry to mess with your issue tracker here, but I can't reply inplace.

I've been getting some mentions on commit/issue message on your hidden repo "PersonalTrainerApp", where sadly I can't reply. I think you might be mistaking my Github handle (@martinnj) for someone elses.
Could you look into it? You can just delete this issue when you see it. :)

Have a nice day!
//Martin

**Comment by axeloh** [comment]
Hey!
I am sorry about that, it should be fixed now. Let me know if you still
keep getting messages!

Axel


ons. 25. apr. 2018 kl. 06.59 skrev Martin J <notifications@github.com>:

**Comment by martinnj** [comment]
No problem, just thought I'd let you know so someone doesn't get left out of the loop. ;)
